services:
  db:
    image: postgres:16
    container_name: kokastyle_db
    restart: always
    environment:
      POSTGRES_DB: kokastyle_postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cyberstalker
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: kokastyle_app
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: cyberstalker
      DB_NAME: kokastyle_postgres
    ports:
      - "8080:8080"
    

volumes:
  pgdata: