definitions:
  models.Login_input:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  models.SignUp_input:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
info:
  contact: {}
paths:
  /:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Root route
      tags:
      - root
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: User credentials (username and password)
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/models.Login_input'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: User login
      tags:
      - auth
  /products:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get list of products
      tags:
      - Products
  /sign_up:
    post:
      consumes:
      - application/json
      parameters:
      - description: Registration data (username, email, password)
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/models.SignUp_input'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: User registration
      tags:
      - auth
swagger: "2.0"
